language: python
dist: trusty
sudo: required

python:
- '3.5'

before_install:
- pip install -U pip
- pip install -r requirements.txt
- git submodule update --init --remote --recursive

script: 
- make publish

# deploy to GitHub pages
deploy:
  provider: pages
  local_dir: output/
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  on:
    branch: master